project_name: maintainers-generator
checksum:
  disable: true
dist: bin
builds:
  - id: "maintainers-generator"
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - make VERBOSE=1 build
        - mv -f bin/maintainers-generator bin/maintainers-generator_linux_amd64/

changelog:
  sort: desc
  filters:
    exclude:
      - "^deps:"
